# Generated by Django 2.1 on 2018-09-23 17:40

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/%r', verbose_name='upload file')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/%r', verbose_name='upload image')),
                ('update_date_time', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('create_date_time', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='PostsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Post Group',
                'verbose_name_plural': 'Posts Group',
            },
        ),
    ]
